Cargo: Remove target key for web-sys
Fix:
```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  'target' specifier cannot be used without an 'artifact = …' value (web-sys)
```

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>